#
# Simple Back-End Kube
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bacque
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bacque
    spec:
      containers:
      - name: bacque-front
        image: maroda/craque:Bv003
        ports:
          - containerPort: 9999
        readinessProbe:
          httpGet:
            path: /ping
            port: 9999
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
      imagePullSecrets:
        - name: crqregcred
---
apiVersion: v1
kind: Service
metadata:
  name: bacque
spec:
  type: NodePort
  selector:
    app: bacque
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9999
