apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bacque
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bacque
    spec:
      containers:
      - name: bacque-front
        image: maroda/craque:Bv003
        ports:
          - containerPort: 9999
      imagePullSecrets:
        - name: crqregcred
---
apiVersion: v1
kind: Service
metadata:
  name: bacque
spec:
  type: NodePort
  selector:
    app: bacque
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9999
