---
#
# Front
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: craque
  namespace: aslsp
  labels:
    app: craque
spec:
  replicas: 3
  selector:
    matchLabels:
      app: craque
  template:
    metadata:
      labels:
        app: craque
        version: 0.3.0
    spec:
      containers:
      - name: craque
        image: maroda/aslsp:0.3.0
        ports:
          - containerPort: 8888
        env:
        - name: BACQUE
          value: "http://bacque/fetch"
        readinessProbe:
          httpGet:
            path: /ping
            port: 8888
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            memory: "8Mi"
            cpu: "125m"
          limits:
            memory: "32Mi"
            cpu: "250m"
---
#
# Front Service
#
apiVersion: v1
kind: Service
metadata:
  name: craque
  namespace: aslsp
  labels:
    app: craque
    service: craque
  annotations:
    prometheus.io/port: "8888"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  selector:
    app: craque
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
