# somewhat generic prometheus config
#
# Is used by the homebrew install in /usr/local/etc/prometheus.args, which is simply:
#
#   --storage.tsdb.path=/usr/local/var/prometheus --config.file ~/dev/github/maroda/aslsp/simple/prom/prometheus.yml
#
#   A writable storage path is required.
#
# Then started with: brew services start prometheus
#
global:
  scrape_interval:     60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # local prometheus metrics
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  # RPiC endpoints
  - job_name: 'craque'
    static_configs:
    - targets: ['192.168.1.32:8888']
  - job_name: 'bacque'
    static_configs:
    - targets: ['192.168.1.34:9999']
