#cloud-config

packages:
  - htop

groups:
  - name: maroda

users:
  - name: maroda
    ssh-authorized-keys:
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtHDQHePgT3SD/5y+xCFKbMDBjUKFrzADTKPYjel6GHpPe58OeORJZWtC6hPKVae4Vjn1CHut3TCymaacdGDtJ3LKZdCjYn93VGPoRNttyODMNo08mY3gt0qyt65hgRp3JGvPHGlscedqVTDLaqOSuslkUXQhVoIHCtgUQwzIG6ADoqPGFJOgGEbPWYY95MObb9uNpVkOmZ+T6+fuee+yuSB4dUq8SnrqAoKuamhD+FMny3zF3C+aWx6Z7fXKmD0/X3+BllpdEnKOsLdQXJvvE69GQxJoIsEgl/1ZICILV8QxFFxtNN/RFws87ouz7LurJdUa4VBNXeQo6ymEGizxx matt@oscillator.localdomain
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    groups: sudo

