#
# Simple Front-End using LoadBalancer
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: craque
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: craque
    spec:
      containers:
      - name: craque-front
        image: maroda/craque:Cv005
        env:
        - name: BACQUE
          value: "http://bacque/fetch"
        ports:
          - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /ping
            port: 8888
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: craque
spec:
  type: LoadBalancer
  selector:
    app: craque
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
