#
# Simple Back-End Kube
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bacque
  labels:
    app: bacque
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bacque
  template:
    metadata:
      labels:
        app: bacque
        version: Bv012
    spec:
      containers:
      - name: bacque-front
        image: maroda/craque:Bv012
        ports:
          - containerPort: 9999
        readinessProbe:
          httpGet:
            path: /ping
            port: 9999
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: bacque
spec:
  type: NodePort
  selector:
    app: bacque
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9999
