{
 "title": "CraqueBox",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Craque Hit Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(craque_fetch_timer_seconds_count[1m]))",
     "legendFormat": "Fetch"
    }
   ]
  },
  {
   "title": "Bacque Hit Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bacque_api_timer_seconds_count[1m]))",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Craque Ave Fetch Timer (1m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(craque_fetch_timer_seconds_sum[1m]) / rate(craque_fetch_timer_seconds_count[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bacque Ave API Timer (1m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bacque_api_timer_seconds_sum[1m]) / rate(bacque_api_timer_seconds_count[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Craque Fetch Quantiles (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(craque_fetch_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(craque_fetch_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(craque_fetch_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(craque_fetch_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Bacque API Quantiles (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(bacque_api_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "100"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(bacque_api_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bacque_api_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(bacque_api_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Craque Fetch Apdex Score (5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(craque_fetch_timer_seconds_bucket{le=\"0.011\"}[5m])) by (job)\n+\nsum(rate(craque_fetch_timer_seconds_bucket{le=\"0.041\"}[5m])) by (job)\n)/2/sum(rate(craque_fetch_timer_seconds_count[5m])) by (job)",
     "legendFormat": "10 - 40ms response"
    }
   ]
  },
  {
   "title": "Bacque API Apdex Score (5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(bacque_api_timer_seconds_bucket{le=\"0.011\"}[5m])) by (job)\n+\nsum(rate(bacque_api_timer_seconds_bucket{le=\"0.041\"}[5m])) by (job)\n)/2/sum(rate(bacque_api_timer_seconds_count[5m])) by (job)",
     "legendFormat": "10 - 40ms response"
    }
   ]
  }
 ]
}