---

docker_version: "18.06.1-ce"
docker_package_file: "docker-{{ docker_version }}.tgz"
docker_download_url: "https://download.docker.com/linux/static/stable/x86_64/{{ docker_package_file }}"
cni_package_file: "cni-amd64-v0.6.0.tgz"
cni_download_url: "https://github.com/containernetworking/cni/releases/download/v0.6.0/{{ cni_package_file }}"
kubernetes_version: "v1.13.0"
kubelet_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64"
