#
# Simple Back-End Kube
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inque-v001
  labels:
    app: inque
    version: Iv001
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: inque
        version: Iv001
    spec:
      containers:
      - name: inque
        image: maroda/craque:Iv001
        ports:
          - containerPort: 7777
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: inque
spec:
  type: LoadBalancer
  selector:
    app: inque
  ports:
  - protocol: TCP
    port: 7777
