#
# Simple Front-End using Istio
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: craque-v010
  labels:
    app: craque
    version: Cv010
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sumologic.com/kubernetes_meta_reduce: "true"
        sumologic.com/include: "true"
      labels:
        app: craque
        version: Cv010
    spec:
      containers:
      - name: craque
        image: maroda/craque:Cv010
        env:
        - name: BACQUE
          # using this istio/mesh served version of bacque *will not expose errors*
          # value: "http://app.craq.io/fetch"
          #
          # instead, use the Kube provided DNS/LB + port
          # this will let app=craque throw the 400 error when bacque is not there
          value: "http://bacque:9999/fetch"
        ports:
          - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /ping
            port: 8888
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8888"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  name: craque
  labels:
    app: craque
    service: craque
spec:
  selector:
    app: craque
  ports:
  - port: 8888
    name: http
