#
# Simple Front-End using Istio
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: craque-v005
  labels:
    app: craque
    version: Cv005
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: craque
        version: Cv005
    spec:
      containers:
      - name: craque
        image: maroda/craque:Cv005
        env:
        - name: BACQUE
          value: "http://app.craq.io/fetch"
        ports:
          - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /ping
            port: 8888
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8888"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  name: craque
  labels:
    app: craque
    service: craque
spec:
  selector:
    app: craque
  ports:
  - port: 8888
    name: http
